### ISSUE TITLE
节点抓取途径收集

### ISSUE THREAD

**Issue by zu1k** [zu1k/proxypool#3]
节点支持的类型见 example/source.yaml

```
sources:
  # 节点订阅地址
  - type: subscribe
    options:
      url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray

  # 公开互联网页面模糊抓取
  - type: webfuzz
    options:
      url: https://merlinblog.xyz/wiki/freess.html

  # telegram频道
  - type: tgchannel
    options:
      channel: ssrList
      num: 200

  # 翻墙党（无需修改）
  - type: web-fanqiangdang
    options:
      url: https://fanqiangdang.com/forum.php?mod=rss&fid=50&auth=0
      num: 200

  # 后面是其他的几个分享站，无需看
  - type: web-freessrxyz
    options:

  - type: web-lucnorg
    options:
```
