### ISSUE TITLE
安卓版Clash不支持ssr模式

### ISSUE THREAD

**Issue by zu1k** [zu1k/proxypool#6]
用户可以自行筛选需要的节点类型，默认全部类型

安卓版Clash目前不支持ssr，可以只保留ss和vmess节点：`https://proxy.tgbot.co/clash/proxies?type=ss,vmess`

此种方式需要用户自行维护配置文件，只需要将目前的配置文件修改其中的链接即可

```yaml
# 修改这里的url那一行，后面加上 ?type=ss,vmess 即可
proxy-providers:
  provider:
    type: http
    url: "https://proxy.tgbot.co/clash/proxies?type=ss,vmess"
    interval: 3600
    path: ./provider.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
```
